account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path("login/",views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.user_register, name="register"),
    path("edit/", views.user_edit , name="edit"),
]

blog/urls.py
from django.urls import path
from.import views

app_name = 'blog'
urlpatterns = [
    path('messages/', views.MessagesListView.as_view(), name='message_list'),
    path('details/<slug:slug>',views.ArticleDetailView.as_view(),name='article_details'),
    path('list',views.ArticleListView.as_view(),name='article_list'),
    path('category/<int:pk>',views.category_detail,name="category_detail"),
    path('search/',views.search,name="search_articles"),
    # path('new/',views.post_new,name='post_new'),
    path('contactus',views.MessageView.as_view(),name='contact_us'),
    path('red/<slug:slug>',views.HomePageRedirect.as_view(),name='redirect'),
    path('messages/edit/<int:pk>',views.MessagesUpdateView.as_view(),name='message_edit'),
    path('messages/delete/<int:pk>',views.MessagesDeleteView.as_view(),name='message_delete'),
    path('archive',views.ArchiveIndexArticleView.as_view(),name='archive'),
    path('archive/<int:year>',views.YearArchiveArticleView.as_view(),name='year_archive'),
    path('like/<slug:slug>/<int:pk>',views.Like,name='like'),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_app.urls')),
    path('',include('account.urls')),
    path('articles/',include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import format_html
from django.utils.text import slugify
# Create your models here.
#article to user
#ManyTOMany
#ManyToOne
#OneToOne
#cascade
#set null

#protect
#set default

class  Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

class ArticleManager(models.Manager):
    def get_queryset(self):
        return super(ArticleManager, self).get_queryset().filter(status=True)



class Article(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='articles',verbose_name="نویسنده ی مقاله")
    category = models.ManyToManyField(Category,related_name='articles', verbose_name="دسته بندی")
    title = models.CharField(max_length=100,verbose_name="عنوان")
    body = models.TextField(verbose_name="توضیحات")
    views = models.IntegerField(null=True,verbose_name="بازدید")
    image = models.ImageField(upload_to='images/articles/',verbose_name="انتخاب تصویر",blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True,verbose_name="زمان ساخت")
    updated = models.DateTimeField(auto_now=True,verbose_name="بروزرسانی")
    myfile = models.FileField(upload_to='test',null=True,verbose_name="انتخاب فایل")
    status = models.BooleanField(default=False,verbose_name="وضعیت دوره")
    published = models.BooleanField(default=False,verbose_name="منتشر شده")
    slug = models.SlugField(unique=True,blank=True)
    pub_date = models.DateTimeField(default=timezone.now,verbose_name="تاریخ")
    objects = models.Manager()
    custom_manager = ArticleManager()




    def save(self,force_insert=False,force_update=False,using=None,update_fields=None):
        self.slug = slugify(self.title)
        super(Article,self).save()


    def get_absolute_url(self):
        return reverse('blog:article_details',kwargs={'slug':self.slug})

    # def print_title(self):            متودی برای جنگو ادمین وخط پایینی برای فارسی کردن نوشته متود درجنگو ادمین#
    #     return self.title
    #
    # print_title.short_description = "چاپ عنوان"



    def show_image(self):
        if self.image:
            return format_html(f'<img src="{self.image.url}" width="50px" height="50px">')
        return format_html('<h3 style="color:red">تصویر ندارد</h3>')
    show_image.short_description = "تصویر"


    def __str__(self):
        return f"{self.title}-{self.body[:30]}"

    class Meta:
        ordering = ('-created',)
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comments')
    parent = models.ForeignKey('self',on_delete=models.CASCADE,related_name='replies',null=True,blank=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"



    def __str__(self):
        return self.body[:50]


class Message(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    email = models.EmailField()
    age = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    date = models.DateTimeField(default=timezone.now())

    class Meta:
        verbose_name = "پیام"
        verbose_name_plural = "پیام ها"



    def __str__(self):
        return self.title



class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='likes',verbose_name="کاربر")
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='likes',verbose_name="مقاله")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.article.title}"


    class Meta:
        verbose_name="لایک"
        verbose_name_plural = "لایک ها"
        ordering = ('-created_at',)

blog/forms.py
from django import forms
from django.core.validators import ValidationError

from blog.models import Message


class ContactUsForm(forms.Form):
    BIRTH_YEAR_CHOICES = ["1980","1981","1982"]
    FAVORITE_COLORS_CHOICES = [
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('red', 'Red'),
    ]
    name = forms.CharField(max_length=10, label="your Name")
    text = forms.CharField(max_length=10,label='your message')
    birth_year = forms.DateField(widget=forms.DateTimeInput(attrs={'class':'form-control'}))
    colors = forms.ChoiceField(choices=FAVORITE_COLORS_CHOICES)
    numbers = forms.IntegerField()

    def clean(self):
        name = self.cleaned_data.get('name')
        text = self.cleaned_data.get('text')
        if name == text:
            raise forms.ValidationError("name can't be same",code="name_text_same")

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'
        widgets = {
            "title":forms.TextInput(attrs={'class':'form-control','placeholder':'inter your title','style':'max-width:300px'}),
            "text":forms.Textarea(attrs={'class':'form-control'}),
        }

blog/views.py
# from email.message import Message
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect,HttpResponse
from django.urls import reverse_lazy,reverse
from blog.models import Article, Category, Comment ,Message,Like
from django.core.paginator import Paginator
from .forms import ContactUsForm,MessageForm
from django.views.generic.base import View,TemplateView ,RedirectView
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView, ArchiveIndexView, YearArchiveView
from.mixins import LoginRequiredMixin

def article_detail(request,slug):
    article = get_object_or_404(Article, slug=slug)
    if request.method == 'POST' :
        parent_id = request.POST.get('parent_id')
        body = request.POST.get('body')
        Comment.objects.create(body=body,article=article,user=request.user,parent_id=parent_id)

    return render(request, "blog/article_details.html", {"article":article})


def article_list(request):
    articles = Article.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 2)
    objects_list =paginator.get_page(page_number)
    return render(request,"blog/articles_list.html",{"articles":objects_list })


def category_detail(request,pk=None):
    category = get_object_or_404(Category,id=pk)
    articles =category.articles.all()
    return  render(request,"blog/articles_list.html",context={"articles":articles})


def search(request):
    q = request.GET.get('q')
    articles = Article.objects.filter(title__icontains=q)
    page_number = request.GET.get('page')
    paginator = Paginator(articles, 2)
    objects_list = paginator.get_page(page_number)
    return render(request,"blog/articles_list.html",{"articles":objects_list})



def contactus(request):
    if request.method == 'POST':
        form = MessageForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=True)
            instance.bmi = instance.weight *instance.height
            return redirect('home_app:home')
    else:
        form = MessageForm()
    return render(request,"blog/contact_us.html",{'form':form})

class TestBaseView(View):
    name ="amir"
    def get(self, request):
        return HttpResponse(self.name)





class BerListView(View):                                                                            #ber:یه حروف الکیه#
    queryset = Article.objects.all()
    template_name = "blog/articles_list.html"

    def get(self, request):
        return render(request, self.template_name, {'object_list': self.queryset})

class HomePageRedirect(RedirectView):
    # url = "/articles/list"
    pattern_name = 'blog:article_details'
    permanent = False
    query_string = False


    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)

class ArticleList(TemplateView):
    pass


class UserList(ListView):
    queryset = User.objects.all()
    template_name = "blog/user_list.html"


class ArticleDetailView(DetailView):
    model = Article
    template_name = "blog/article_details.html"
    # context_object_name = "art"
    # slug_field = 'karim'
    # queryset = Article.objects.filter(published=True)******************************
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['name'] = "amir"
    #     return context


class ArticleListView(LoginRequiredMixin,ListView):
    model = Article
    context_object_name = "articles"
    paginate_by = 2
    template_name = "blog/articles_list.html"


class ContactUsView(FormView):
    template_name = "blog/contact_us.html"
    form_class = MessageForm
    success_url = "/"

    def form_valid(self, form):
        from_data = form.cleaned_data
        Message.objects.create(**from_data )
        return super().form_valid(form)


class MessageView(CreateView):
    model = Message
    fields = ('title','text','date', 'age')
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['messages'] = Message.objects.all()
        return context


    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.email = self.request.user.email
        instance.save()
        return super().form_valid(form)

    def get_success_url(self):
        print(self.object)
        return super(MessageView, self).get_success_url()

class MessagesListView(ListView):
    model = Message
class MessagesUpdateView(UpdateView):
    model = Message
    fields = ('title','text', 'age')
    template_name = "blog/message_update_form.html"
    success_url = reverse_lazy("blog:message_list")

class MessagesDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("blog:message_list")


class ArchiveIndexArticleView(ArchiveIndexView):
    model = Article
    date_field = 'updated'

class YearArchiveArticleView(YearArchiveView):
    model = Article
    date_field = 'pub_date'
    make_object_list = True
    allow_future = True

def like(request, slug, pk):
    try:
        like = Like.objects.get(article_slug=slug,user_id=request.user.id)
        like.delete()
    except Like.DoesNotExist:
        Like.objects.create(article_id=pk,user_id=request.user.id)
    return redirect('blog:article_details',slug=slug)

blog/templates/blog/article_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for article in latest %}
        <li>{{ article.updated }}: {{ article.title }}</li>
    {% endfor %}
</ul>
</body>
</html>

blog/templates/blog/article_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
    {% for date in date_list %}
        <li>{{ date|date }}</li>
    {% endfor %}
</ul>

<div>
    <h1>All Articles for {{ year|date:"Y" }}</h1>
    {% for obj in object_list %}
        <p>
            {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }} - {{ next_year }}
        </p>
    {% endfor %}
</div>
</body>
</html>

blog/templates/blog/article_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
        <section class="page-heading">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-content">
                            <h4>Article Details</h4>
                            <h2>{{ article.title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Banner Ends Here -->


    <section class="blog-posts grid-system">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="all-blog-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="{{ article.image.url }}" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>Lifestyle</span>
                                        <a href="post-details.html"><h4>{{ article.title }}</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">{{ article.author.get_full_name }}</a></li>
                                            <li><a href="#">{{ article.created }}</a></li>
                                            <li><a href="#">{{ article.comment }}</a></li>
                                        </ul>
                                        <p>{{ article.body }}</p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-heart">
                                                        <li><a href="{% url 'blog:like' article.slug article.id %}"><i style="font-size: 20px" class="fa fa-heart-o " ></i></a>2</li>

                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#"> Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="sidebar-item comments">
                                    <div class="sidebar-heading">
                                        <h2>{{ object.comments }}</h2>
                                    </div>
                                    <div class="content">
                                        <ul>
                                            {% for comment in article.comments.all %}
                                                {% if comment.parent == None %}
                                                    <li>
                                                        <div class="author-thumb">
                                                            {% if comment.user.profile.image %}
                                                                <img src="{{ comment.user.profile.image.url }}"
                                                                     alt="">
                                                            {% else %}
                                                                <img src="{% static 'images/icons/images (1).png' %}"
                                                                     alt="amir">
                                                            {% endif %}
                                                        </div>
                                                        <div class="right-content">
                                                            <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_at }}</span>
                                                            </h4>
                                                            <p>{{ comment.body }}</p>
                                                            <button onclick="set_value({{ comment.id }})"
                                                                    class="btn btn-primary rounded-pill">reply
                                                            </button>
                                                        </div>
                                                    </li>
                                                    {% for reply in comment.replies.all %}
                                                        <li class="replied">
                                                            <div class="author-thumb">
                                                                {% if comment.user.profile.image %}
                                                                    <img src="{{ comment.user.profile.image.url }}"
                                                                         alt="amir">
                                                                {% else %}
                                                                    <img src="{% static 'images/icons/images (1).png' %}"
                                                                         alt="">
                                                                {% endif %}

                                                            </div>
                                                            <div class="right-content">
                                                                <h4>{{ reply.user.get_full_name }}<span>{{ reply.created_at }}</span>
                                                                </h4>
                                                                <p>{{ reply.body }}</p>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% endif %}

                                            {% endfor %}


                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% if request.user.is_authenticated %}
                                <div class="col-lg-12">
                                    <div class="sidebar-item submit-comment">
                                        <div class="sidebar-heading">
                                            <h2 id="hi">Your comment</h2>
                                        </div>
                                        <div class="content">
                                            <form id="comment" action="#" method="post">
                                                {% csrf_token %}
                                                <div class="row">
                                                    <input type="hidden" id="parent_id" name="parent_id" value="">
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                        <textarea name="body" rows="6" id="body"
                                                                  placeholder="Type your comment"
                                                                  required=""></textarea>
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Submit
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                                <a class="btn btn-danger mt-2" href="{% url 'account:register' %}">for sending comment
                                    please register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% include "includes/sidebar.html" %}
            </div>
        </div>
    </section>
    <script>

        function set_value(id) {
            document.getElementById('parent_id').value = id;
            window.location.href = '#body';


        }


    </script>
{% endblock %}

    

blog/templates/blog/article_list2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for user in object_list %}
    <p>{{ user.title }}</p>
{% endfor %}
</body>
</html>

blog/templates/blog/contact_us.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}contact us{% endblock %}
{% block content %}
    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                {{ form.text.errors }}
                                                <div class="col-lg-12">
                                                    {{ form }}
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Send
                                                                Message
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/message_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}contact us{% endblock %}
{% block content %}
    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        {% for m in message_list %}
                                            <p>{{ m.title }} - {{ m.text|truncatewords:20 }} - {{ m.age }} - <span><a href="{% url "blog:message_edit" m.id %}" class="btn btn-primary ml-1">Edit</a></span>
                                                <hr>
                                            </p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
{#                    <div id="map">#}
{#                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"#}
{#                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>#}
{#                    </div>#}
                </div>

            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/message_update_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}contact us{% endblock %}
{% block content %}
    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        <form id="contact" action="" method="post">
                                            {% csrf_token %}
                                            <div class="row">
                                                {{ form.text.errors }}
                                                <div class="col-lg-12">
                                                    {{ form }}
                                                    <a href="{% url "blog:message_delete" object.id %}" class="btn btn-danger mb-2 ml-3">delete</a>
                                                    <div class="col-lg-12">
                                                        <fieldset>
                                                            <button type="submit" id="form-submit" class="main-button">
                                                                Submit
                                                            </button>
                                                        </fieldset>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

blog/templates/blog/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for user in object_list %}
    <p>{{ user.get_full_name }}</p>
{% endfor %}
</body>
</html>